import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import { themes as prismThemes } from 'prism-react-renderer';
import * as path from 'path';

// The docs corpus lives at the repo root (`docs/`), not inside `website/`,
// so it stays covered by `__tests__/docs-examples.test.ts` and readable on
// GitHub. `docs/api` is generated by typedoc (gitignored).
const config: Config = {
  title: 'pptx-automizer',
  tagline: 'A template-based .pptx generator for Node.js',

  // GitHub Pages is the only deploy target; the env overrides are a generic
  // escape hatch for building against another host (unused by CI).
  url: process.env.DOCS_URL ?? 'https://singerla.github.io',
  baseUrl: process.env.DOCS_BASE_URL ?? '/pptx-automizer/',
  organizationName: 'singerla',
  projectName: 'pptx-automizer',
  trailingSlash: false,

  onBrokenLinks: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    // .md (the whole corpus + typedoc output) is CommonMark: OOXML tags and
    // generics in prose must not be parsed as JSX. Opt into MDX per-file
    // by using the .mdx extension.
    format: 'detect',
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: '../docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: ({ docPath }) =>
            // typedoc output is generated — no edit link
            docPath.startsWith('api/')
              ? undefined
              : `https://github.com/singerla/pptx-automizer/edit/main/docs/${docPath}`,
        },
        blog: false,
        pages: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: [path.resolve(__dirname, '../src/index.ts')],
        tsconfig: path.resolve(__dirname, '../tsconfig.json'),
        out: path.resolve(__dirname, '../docs/api'),
        readme: 'none',
        excludePrivate: true,
        excludeInternal: true,
        // src doc comments cite raw OOXML tags (`<a:ln>` …); escape them so
        // MDX does not parse them as JSX
        sanitizeComments: true,
        sidebar: { autoConfiguration: true, pretty: true },
      },
    ],
  ],

  themes: [
    [
      // compile-time local search index — no hosted search service (ROADMAP 6.3)
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        docsDir: '../docs',
        docsRouteBasePath: '/',
        indexBlog: false,
        indexPages: false,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'pptx-automizer',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/api',
          position: 'left',
          label: 'API',
        },
        {
          href: 'https://www.npmjs.com/package/pptx-automizer',
          label: 'npm',
          position: 'right',
        },
        {
          href: 'https://github.com/singerla/pptx-automizer',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Getting started', to: '/' },
            { label: 'API reference', to: '/api' },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/singerla/pptx-automizer',
            },
            {
              label: 'npm',
              href: 'https://www.npmjs.com/package/pptx-automizer',
            },
            {
              label: 'Changelog',
              href: 'https://github.com/singerla/pptx-automizer/blob/main/CHANGELOG.md',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Thomas Singer. MIT licensed.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // the docs' code blocks are TypeScript throughout
      defaultLanguage: 'typescript',
      additionalLanguages: ['bash', 'json'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
