import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The guides sidebar is maintained by hand — new pages in `docs/` get their id
// added here. `docs/api/typedoc-sidebar.cjs` is generated by
// docusaurus-plugin-typedoc on every build (also via `yarn docs:api` from the
// repo root).
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'getting-started',
    'concepts',
    'selectors',
    {
      type: 'category',
      label: 'Modify content',
      collapsed: false,
      items: ['text', 'tables', 'charts', 'images', 'masters-layouts'],
    },
    'generation',
    'hyperlinks',
    'slide-management',
    'helpers',
    'output',
    'limitations',
    'troubleshooting',
    'testing',
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: require('../docs/api/typedoc-sidebar.cjs'),
    },
  ],
};

export default sidebars;
