import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The guides sidebar is maintained by hand: the ROADMAP 6.2 README split adds
// its pages here one by one (getting-started, concepts, selectors, …).
// `docs/api/typedoc-sidebar.cjs` is generated by docusaurus-plugin-typedoc on
// every build (also via `yarn docs:api` from the repo root).
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: require('../docs/api/typedoc-sidebar.cjs'),
    },
  ],
};

export default sidebars;
