import fs from 'fs';
import JSZip from 'jszip';
import { DOMParser, Element as XmlElement } from '@xmldom/xmldom';
import Automizer, { modify } from '../src/index';
import { ChartData } from '../src/types/chart-types';

/**
 * Excel skips the <c>-element of an empty cell. A chart worksheet with an
 * empty cell A1 therefore starts its first row with <c r="B1">, which used to
 * shift all following cells and finally create duplicate cell addresses.
 * See https://github.com/singerla/pptx-automizer/issues/39
 *
 * The chart worksheet of "ColumnsGroupedEmptyA1" has a cleared cell A1, but as
 * its data is stored in a worksheet table, Excel keeps a "Spalte1" placeholder
 * instead of removing the <c>-element. A worksheet with a truly missing cell is
 * therefore created by createTemplateWithEmptyCells().
 */

const templateDir = `${__dirname}/pptx-templates`;
const outputDir = `${__dirname}/pptx-output`;

const chartName = `ColumnsGroupedEmptyA1`;

// The worksheet of "ColumnsGroupedEmptyA1" on slide 2 of ChartBarsStacked.pptx
const chartWorksheet = `ppt/embeddings/Microsoft_Excel_Worksheet1.xlsx`;

// Generated by createTemplateWithEmptyCells(), loaded relative to templateDir
const emptyCellTemplate = `ChartBarsStackedEmptyCells.pptx`;
const emptyCellTemplatePath = `../pptx-output/${emptyCellTemplate}`;

// A missing label cell and a missing value cell
const emptyCells = ['A1', 'B3'];

// The name of the first tableColumn, PowerPoint's placeholder for a cleared A1
const firstColumnLabel = `Spalte1`;

const chartData = <ChartData>{
  series: [{ label: 'series 1' }, { label: 'series 2' }],
  categories: [
    { label: 'cat 2-1', values: [50, 55] },
    { label: 'cat 2-2', values: [14, 55] },
    { label: 'cat 2-3', values: [15, 55] },
  ],
};

beforeAll(async () => {
  await createTemplateWithEmptyCells();
});

test('modify a chart with empty cells in its worksheet', async () => {
  const outputFile = `modify-chart-empty-cells.test.pptx`;
  await modifyChart(emptyCellTemplatePath, outputFile);

  const worksheet = await readChartWorksheet(outputFile);

  expect(worksheet.addresses(0)).toEqual(['A1', 'B1', 'C1']);
  expect(worksheet.addresses(2)).toEqual(['A3', 'B3', 'C3']);
  expect(worksheet.duplicateAddresses()).toEqual([]);

  // A restored header cell needs to match the name of its tableColumn.
  expect(worksheet.value('A1')).toBe(firstColumnLabel);
  expect(worksheet.tableColumns()[0]).toBe(firstColumnLabel);

  expect(worksheet.value('B1')).toBe('series 1');
  expect(worksheet.value('C1')).toBe('series 2');

  expect(worksheet.value('A2')).toBe('cat 2-1');
  expect(worksheet.value('B2')).toBe('50');
  expect(worksheet.value('C4')).toBe('55');

  // A restored value cell must not point to a shared string.
  expect(worksheet.isSharedString('B3')).toBe(false);
  expect(worksheet.value('B3')).toBe('14');
});

test('modify the same chart with a complete worksheet', async () => {
  const outputFile = `modify-chart-empty-cells-untouched.test.pptx`;
  await modifyChart(`ChartBarsStacked.pptx`, outputFile);

  const worksheet = await readChartWorksheet(outputFile);

  // Nothing is inserted into a worksheet without gaps.
  expect(worksheet.addresses(0)).toEqual(['A1', 'B1', 'C1']);
  expect(worksheet.duplicateAddresses()).toEqual([]);

  // The cleared cell A1 keeps its placeholder.
  expect(worksheet.value('A1')).toBe(firstColumnLabel);
  expect(worksheet.tableColumns()[0]).toBe(firstColumnLabel);

  expect(worksheet.value('B1')).toBe('series 1');
  expect(worksheet.value('C4')).toBe('55');
});

const modifyChart = async (
  template: string,
  outputFile: string,
): Promise<void> => {
  const automizer = new Automizer({
    templateDir,
    outputDir,
  });

  await automizer
    .loadRoot(`RootTemplate.pptx`)
    .load(template, 'charts')
    .addSlide('charts', 2, (slide) => {
      slide.modifyElement(chartName, [modify.setChartData(chartData)]);
    })
    .write(outputFile);
};

/**
 * Removes the <c>-elements of cell A1 and B3 from the chart worksheet, exactly
 * as Excel would store it if the user cleared these cells.
 */
const createTemplateWithEmptyCells = async (): Promise<void> => {
  const template = await JSZip.loadAsync(
    fs.readFileSync(`${templateDir}/ChartBarsStacked.pptx`),
  );
  const workbook = await JSZip.loadAsync(
    await template.file(chartWorksheet).async('nodebuffer'),
  );

  const sheetPath = 'xl/worksheets/sheet1.xml';
  const sheet = await workbook.file(sheetPath).async('text');
  const strippedSheet = emptyCells
    .reduce(
      (xml, address) =>
        xml.replace(new RegExp(`<c r="${address}"[^>]*>.*?</c>`), ''),
      sheet,
    )
    .replace('<row r="1" spans="1:4"', '<row r="1" spans="2:4"');

  emptyCells.forEach((address) => {
    expect(strippedSheet).not.toContain(`r="${address}"`);
  });

  workbook.file(sheetPath, strippedSheet);
  template.file(
    chartWorksheet,
    await workbook.generateAsync({ type: 'nodebuffer' }),
  );

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(
    `${outputDir}/${emptyCellTemplate}`,
    await template.generateAsync({ type: 'nodebuffer' }),
  );
};

/**
 * Locates the worksheet of the modified chart in a written pptx and exposes
 * its cells by address.
 */
const readChartWorksheet = async (
  outputFile: string,
): Promise<ChartWorksheet> => {
  const archive = await JSZip.loadAsync(
    fs.readFileSync(`${outputDir}/${outputFile}`),
  );

  const slide = await findPart(archive, /^ppt\/slides\/slide\d+\.xml$/, (xml) =>
    xml.includes(chartName),
  );
  const chart = await relationshipTarget(archive, slide, 'ppt/charts/');
  const embedding = await relationshipTarget(archive, chart, 'ppt/embeddings/');

  const workbook = await JSZip.loadAsync(
    await archive.file(embedding).async('nodebuffer'),
  );

  return new ChartWorksheet(
    await workbook.file('xl/worksheets/sheet1.xml').async('text'),
    await workbook.file('xl/sharedStrings.xml').async('text'),
    await workbook.file('xl/tables/table1.xml').async('text'),
  );
};

const findPart = async (
  archive: JSZip,
  pattern: RegExp,
  matches: (xml: string) => boolean,
): Promise<string> => {
  for (const name of Object.keys(archive.files)) {
    if (pattern.test(name) && matches(await archive.file(name).async('text'))) {
      return name;
    }
  }
  throw new Error(`No part matching ${pattern} found`);
};

const relationshipTarget = async (
  archive: JSZip,
  part: string,
  targetPrefix: string,
): Promise<string> => {
  const relsPath = part.replace(/([^/]+)$/, '_rels/$1.rels');
  const rels = await archive.file(relsPath).async('text');
  const target = rels.match(
    new RegExp(`Target="\\.\\./${targetPrefix.split('/')[1]}/([^"]+)"`),
  );

  if (!target) {
    throw new Error(`No ${targetPrefix} relationship in ${relsPath}`);
  }

  return targetPrefix + target[1];
};

class ChartWorksheet {
  private readonly rows: XmlElement[];
  private readonly strings: string[];
  private readonly columns: string[];

  constructor(sheetXml: string, sharedStringsXml: string, tableXml: string) {
    const parser = new DOMParser();
    this.rows = Array.from(
      parser
        .parseFromString(sheetXml, 'application/xml')
        .getElementsByTagName('row'),
    );
    this.strings = Array.from(
      parser
        .parseFromString(sharedStringsXml, 'application/xml')
        .getElementsByTagName('si'),
    ).map((si) => si.textContent);
    this.columns = Array.from(
      parser
        .parseFromString(tableXml, 'application/xml')
        .getElementsByTagName('tableColumn'),
    ).map((column) => column.getAttribute('name'));
  }

  tableColumns(): string[] {
    return this.columns;
  }

  cells(row?: number): XmlElement[] {
    const rows = row === undefined ? this.rows : [this.rows[row]];
    return rows.reduce(
      (cells, current) => [
        ...cells,
        ...Array.from(current.getElementsByTagName('c')),
      ],
      [] as XmlElement[],
    );
  }

  addresses(row?: number): string[] {
    return this.cells(row).map((cell) => cell.getAttribute('r'));
  }

  duplicateAddresses(): string[] {
    const addresses = this.addresses();
    return addresses.filter((address, i) => addresses.indexOf(address) !== i);
  }

  cell(address: string): XmlElement {
    const cell = this.cells().find((c) => c.getAttribute('r') === address);
    if (!cell) {
      throw new Error(`Worksheet has no cell ${address}`);
    }
    return cell;
  }

  isSharedString(address: string): boolean {
    return this.cell(address).getAttribute('t') === 's';
  }

  value(address: string): string {
    const cell = this.cell(address);
    const value = cell.getElementsByTagName('v')[0]?.textContent ?? '';

    if (!this.isSharedString(address)) {
      return value;
    }

    const sharedString = this.strings[Number(value)];
    if (sharedString === undefined) {
      throw new Error(
        `Cell ${address} refers to unknown shared string ${value}`,
      );
    }

    return sharedString.trim();
  }
}
